COMPIL_SERVER = javac
FLAG_SERVER =
NAME_SERVER = Server

COMPIL_CLIENT = javac
FLAG_CLIENT =
NAME_CLIENT = Client

all: $(NAME_SERVER).class $(NAME_CLIENT).class

$(NAME_SERVER).class: $(NAME_SERVER).java
		$(COMPIL_SERVER) $(FLAG_SERVER) $(NAME_SERVER).java

$(NAME_CLIENT).class: $(NAME_CLIENT).java
	$(COMPIL_CLIENT) $(FLAG_CLIENT) $(NAME_CLIENT).java

clean:
	rm $(NAME_SERVER).class
	rm $(NAME_CLIENT).class
